# Loan Rejection Behavior Analysis

## 1. Import Required Libraries

In this step, we import the necessary Python libraries required for:

- Data loading and manipulation
- Numerical computations
- Data analysis and transformation
- Feature engineering
- File export

These libraries support the data preprocessing and analytics pipeline for the loan dataset.

In [67]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

## Data Loading

In this step, we load the raw loan dataset into a DataFrame for further processing.

This step is responsible for:

- Reading the dataset from a CSV file
- Creating a structured DataFrame
- Preparing data for cleaning and transformation

This forms the data ingestion layer of the analytics pipeline

In [68]:
df = pd.read_csv(r"C:\Users\sai\OneDrive\Desktop\Loan_Project\loan_dataset.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [69]:
df.head()

,Applicant_ID,Age,Gender,Marital_Status,Dependents,Education,Employment_Type,Income,Coapplicant_Income,Credit_Score,Existing_Loans,Loan_Amount,Loan_Term_Months,Property_Area,Loan_Purpose,Debt_to_Income_Ratio,Loan_Status
0,1,59,Male,Married,0,Not Graduate,Salaried,101423.0,42744,649.0,2,361838,60,Rural,Home,0.65,Rejected
1,2,49,Female,Married,4,Graduate,Salaried,63194.0,21885,870.0,0,330817,24,Rural,Home,0.44,Rejected
2,3,35,Female,Married,3,Graduate,Salaried,37249.0,40076,569.0,2,129187,36,Urban,Business,0.21,Rejected
3,4,28,Female,Single,2,Graduate,Salaried,29171.0,63949,619.0,4,460694,60,Urban,Education,0.41,Rejected
4,5,41,Male,Single,4,Graduate,Salaried,134418.0,29658,832.0,2,172518,36,Rural,Education,0.47,Rejected

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 17 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Applicant_ID          500000 non-null  int64
 1   Age                   500000 non-null  int64
 2   Gender                500000 non-null  object
 3   Marital_Status        500000 non-null  object
 4   Dependents            500000 non-null  int64
 5   Education             500000 non-null  object
 6   Employment_Type       500000 non-null  object
 7   Income                492500 non-null  float64
 8   Coapplicant_Income    500000 non-null  int64
 9   Credit_Score          492500 non-null  float64
 10  Existing_Loans        500000 non-null  int64
 11  Loan_Amount           500000 non-null  int64
 12  Loan_Term_Months      500000 non-null  int64
 13  Property_Area         500000 non-null  object
 14  Loan_Purpose          500000 non-null  object
 15  Debt_to_Income_Ratio  500000 non-null  float64
 16  Loan_Status           500000 non-null  object
dtypes: float64(3), int64(7), object(7)
memory usage: 64.8+ MB

In [71]:
df.describe()

,Applicant_ID,Age,Dependents,Income,Coapplicant_Income,Credit_Score,Existing_Loans,Loan_Amount,Loan_Term_Months,Debt_to_Income_Ratio
count,500000.000000,500000.000000,500000.000000,492500.000000,500000.000000,492500.000000,500000.000000,500000.000000,500000.000000,500000.000000
mean,250000.500000,40.020120,1.999672,82530.605364,40026.843590,599.718248,2.004572,274844.576018,35.976432,0.399537
std,144337.711634,11.253559,1.414045,38953.569420,23086.757647,173.266446,1.413694,129855.695218,16.966201,0.173200
min,1.000000,21.000000,0.000000,15001.000000,0.000000,300.000000,0.000000,50001.000000,12.000000,0.100000
25%,125000.750000,30.000000,1.000000,48785.750000,20028.000000,450.000000,1.000000,162369.000000,24.000000,0.250000
50%,250000.500000,40.000000,2.000000,82577.000000,40075.000000,600.000000,2.000000,274563.500000,36.000000,0.400000
75%,375000.250000,50.000000,3.000000,116228.000000,60014.250000,750.000000,3.000000,387428.250000,48.000000,0.550000
max,500000.000000,59.000000,4.000000,149999.000000,79999.000000,899.000000,4.000000,499997.000000,60.000000,0.700000

In [72]:
df.dtypes

Applicant_ID              int64
Age                       int64
Gender                   object
Marital_Status           object
Dependents                int64
Education                object
Employment_Type          object
Income                  float64
Coapplicant_Income        int64
Credit_Score            float64
Existing_Loans            int64
Loan_Amount               int64
Loan_Term_Months          int64
Property_Area            object
Loan_Purpose             object
Debt_to_Income_Ratio    float64
Loan_Status              object
dtype: object

In [73]:
df.isnull().sum()

Applicant_ID               0
Age                        0
Gender                     0
Marital_Status             0
Dependents                 0
Education                  0
Employment_Type            0
Income                  7500
Coapplicant_Income         0
Credit_Score            7500
Existing_Loans             0
Loan_Amount                0
Loan_Term_Months           0
Property_Area              0
Loan_Purpose               0
Debt_to_Income_Ratio       0
Loan_Status                0
dtype: int64

## Data Cleaning

In this step, we clean and preprocess the raw dataset to ensure data quality and consistency before analysis.

This step is responsible for:

- Handling missing values
 -Standardizing data formats
- Fixing inconsistencies in categorical variables
- Preparing data for feature engineering

This forms the data preprocessing layer of the analytics pipeline.

## Handle Missing Values

In [74]:
# Income → median
df['Income'].fillna(df['Income'].median(), inplace=True)

# Credit Score → median
df['Credit_Score'].fillna(df['Credit_Score'].median(), inplace=True)

In [75]:
df.isnull().sum()

Applicant_ID            0
Age                     0
Gender                  0
Marital_Status          0
Dependents              0
Education               0
Employment_Type         0
Income                  0
Coapplicant_Income      0
Credit_Score            0
Existing_Loans          0
Loan_Amount             0
Loan_Term_Months        0
Property_Area           0
Loan_Purpose            0
Debt_to_Income_Ratio    0
Loan_Status             0
dtype: int64

## Feature Engineering

In this step, we transform cleaned data into business-relevant features that help analyze loan approval and rejection behavior.

This step is responsible for:

- Creating financial risk indicators
- Segmenting customers
- Building analytical features for SQL & dashboards

This forms the business logic layer of the analytics pipeline.

### Income to Loan Ratio

In [76]:
df['Income_to_Loan_Ratio'] = df['Income'] / df['Loan_Amount']

df['Income_to_Loan_Ratio'] = df['Income_to_Loan_Ratio'].round(3)

### Credit Score Segmentation

In [77]:
df['Credit_Category'] = pd.cut(
    df['Credit_Score'],
    bins=[300, 600, 700, 950],
    labels=['Poor', 'Average', 'Good']
)

### Debt Burden Category

In [78]:
max_val = df['Debt_to_Income_Ratio'].max()

# Ensure last bin is always greater than 1
upper = max(max_val, 1) + 0.01

df['debt_burden'] = pd.cut(
    df['Debt_to_Income_Ratio'],
    bins=[0, 0.3, 0.6, 1, upper],
    labels=['Low', 'Medium', 'High', 'Very High'],
    include_lowest=True
)

In [79]:
df.head()

,Applicant_ID,Age,Gender,Marital_Status,Dependents,Education,Employment_Type,Income,Coapplicant_Income,Credit_Score,Existing_Loans,Loan_Amount,Loan_Term_Months,Property_Area,Loan_Purpose,Debt_to_Income_Ratio,Loan_Status,Income_to_Loan_Ratio,Credit_Category,debt_burden
0,1,59,Male,Married,0,Not Graduate,Salaried,101423.0,42744,649.0,2,361838,60,Rural,Home,0.65,Rejected,0.280,Average,High
1,2,49,Female,Married,4,Graduate,Salaried,63194.0,21885,870.0,0,330817,24,Rural,Home,0.44,Rejected,0.191,Good,Medium
2,3,35,Female,Married,3,Graduate,Salaried,37249.0,40076,569.0,2,129187,36,Urban,Business,0.21,Rejected,0.288,Poor,Low
3,4,28,Female,Single,2,Graduate,Salaried,29171.0,63949,619.0,4,460694,60,Urban,Education,0.41,Rejected,0.063,Average,Medium
4,5,41,Male,Single,4,Graduate,Salaried,134418.0,29658,832.0,2,172518,36,Rural,Education,0.47,Rejected,0.779,Good,Medium

### Age Group Segmentation

In [80]:
df['Age_Group'] = pd.cut(
    df['Age'],
    bins=[20,30,40,50,60],
    labels=['20-30','30-40','40-50','50-60']
)

In [81]:
df.head()

,Applicant_ID,Age,Gender,Marital_Status,Dependents,Education,Employment_Type,Income,Coapplicant_Income,Credit_Score,...,Loan_Amount,Loan_Term_Months,Property_Area,Loan_Purpose,Debt_to_Income_Ratio,Loan_Status,Income_to_Loan_Ratio,Credit_Category,debt_burden,Age_Group
0,1,59,Male,Married,0,Not Graduate,Salaried,101423.0,42744,649.0,...,361838,60,Rural,Home,0.65,Rejected,0.280,Average,High,50-60
1,2,49,Female,Married,4,Graduate,Salaried,63194.0,21885,870.0,...,330817,24,Rural,Home,0.44,Rejected,0.191,Good,Medium,40-50
2,3,35,Female,Married,3,Graduate,Salaried,37249.0,40076,569.0,...,129187,36,Urban,Business,0.21,Rejected,0.288,Poor,Low,30-40
3,4,28,Female,Single,2,Graduate,Salaried,29171.0,63949,619.0,...,460694,60,Urban,Education,0.41,Rejected,0.063,Average,Medium,20-30
4,5,41,Male,Single,4,Graduate,Salaried,134418.0,29658,832.0,...,172518,36,Rural,Education,0.47,Rejected,0.779,Good,Medium,40-50

### Risk Score

In [82]:
df['Risk_Score'] = (
    (850 - df['Credit_Score']) / 550 * 50 +   # normalized credit risk
    df['Debt_to_Income_Ratio'] * 50                            # DTI contribution
)
df['Risk_Score'] = df['Risk_Score'].round(1)

In [83]:
df.head()

,Applicant_ID,Age,Gender,Marital_Status,Dependents,Education,Employment_Type,Income,Coapplicant_Income,Credit_Score,...,Loan_Term_Months,Property_Area,Loan_Purpose,Debt_to_Income_Ratio,Loan_Status,Income_to_Loan_Ratio,Credit_Category,debt_burden,Age_Group,Risk_Score
0,1,59,Male,Married,0,Not Graduate,Salaried,101423.0,42744,649.0,...,60,Rural,Home,0.65,Rejected,0.280,Average,High,50-60,50.8
1,2,49,Female,Married,4,Graduate,Salaried,63194.0,21885,870.0,...,24,Rural,Home,0.44,Rejected,0.191,Good,Medium,40-50,20.2
2,3,35,Female,Married,3,Graduate,Salaried,37249.0,40076,569.0,...,36,Urban,Business,0.21,Rejected,0.288,Poor,Low,30-40,36.0
3,4,28,Female,Single,2,Graduate,Salaried,29171.0,63949,619.0,...,60,Urban,Education,0.41,Rejected,0.063,Average,Medium,20-30,41.5
4,5,41,Male,Single,4,Graduate,Salaried,134418.0,29658,832.0,...,36,Rural,Education,0.47,Rejected,0.779,Good,Medium,40-50,25.1

### High Risk Flag

In [84]:
df['High_Risk'] = np.where(df['Risk_Score'] > 50, 1, 0)

In [85]:
df.head()

,Applicant_ID,Age,Gender,Marital_Status,Dependents,Education,Employment_Type,Income,Coapplicant_Income,Credit_Score,...,Property_Area,Loan_Purpose,Debt_to_Income_Ratio,Loan_Status,Income_to_Loan_Ratio,Credit_Category,debt_burden,Age_Group,Risk_Score,High_Risk
0,1,59,Male,Married,0,Not Graduate,Salaried,101423.0,42744,649.0,...,Rural,Home,0.65,Rejected,0.280,Average,High,50-60,50.8,1
1,2,49,Female,Married,4,Graduate,Salaried,63194.0,21885,870.0,...,Rural,Home,0.44,Rejected,0.191,Good,Medium,40-50,20.2,0
2,3,35,Female,Married,3,Graduate,Salaried,37249.0,40076,569.0,...,Urban,Business,0.21,Rejected,0.288,Poor,Low,30-40,36.0,0
3,4,28,Female,Single,2,Graduate,Salaried,29171.0,63949,619.0,...,Urban,Education,0.41,Rejected,0.063,Average,Medium,20-30,41.5,0
4,5,41,Male,Single,4,Graduate,Salaried,134418.0,29658,832.0,...,Rural,Education,0.47,Rejected,0.779,Good,Medium,40-50,25.1,0

### Connect Python to MySQL & Upload Data

In this step, we establish a connection between Python and MySQL and store the processed dataset into a relational database.

This step is responsible for:

- Creating a secure database connection
- Handling special characters in credentials
- Exporting cleaned data into MySQL
- Preparing data for SQL-based analysis

This forms the data storage layer of the analytics pipeline.

In [86]:
from sqlalchemy import create_engine
import urllib.parse

# Encode password
password = urllib.parse.quote_plus("Saibaba@1234")

# FIX: disable SSL + stable connection
engine = create_engine(
    f"mysql+mysqlconnector://root:{password}@localhost/Loan_Analysis?ssl_disabled=true"
)

#  MOST IMPORTANT: chunk loading
df.to_sql(
    name='loan_dataset',
    con=engine,
    if_exists='replace',
    index=False,
    chunksize=5000   # smaller chunks = stable
)

print(" Data uploaded successfully")

 Data uploaded successfully